Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Networkteam.Neos.PasswordReset:
          - 'NodeTypes/*'
    fusion:
      autoInclude:
        'Networkteam.Neos.PasswordReset': true
  Flow:
    mvc:
      routes:
        'Networkteam.Neos.PasswordReset': true

Networkteam:
  Neos:
    PasswordReset:
      authenticationProviders:
        - Networkteam.Neos.FrontendLogin:Frontend
      senderAddress: 'no-reply@organisation.org'
      templatePaths:
        noAccountMailHtml: 'resource://Networkteam.Neos.PasswordReset/Private/Templates/Mail/password-reset-help.html'
        noAccountMailTxt: 'resource://Networkteam.Neos.PasswordReset/Private/Templates/Mail/password-reset-help.txt'
        resetPasswordMailHtml: 'resource://Networkteam.Neos.PasswordReset/Private/Templates/Mail/password-reset-link.html'
        resetPasswordMailTxt: 'resource://Networkteam.Neos.PasswordReset/Private/Templates/Mail/password-reset-link.txt'
      sendResetPasswordMail: true
      sendNoAccountMail: true
      # Regular expression pattern without starting and ending delimiters (so it works with html input pattern attribute)
      # This pattern means: Must contain at least one number and one uppercase and lowercase letter, and at least 12 or more characters
      passwordPattern: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{12,}'
